// Autogenerated from Pigeon (v18.x), do not edit directly.
// Run: dart run pigeon --input pigeons/vpn_api.dart
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

// ─────────────────────────────────────────────
// DTOs
// ─────────────────────────────────────────────

class TunnelConfigDto {
  TunnelConfigDto({
    required this.id,
    required this.name,
    required this.serverHost,
    required this.serverPort,
    required this.transportType,
    this.authToken,
    required this.deviceId,
    required this.mtu,
    required this.dnsServers,
    required this.ipv4Address,
    required this.ipv4SubnetMask,
    required this.allowedIPv4Routes,
    required this.excludedIPv4Routes,
    required this.keepAliveSeconds,
    required this.workers,
    this.sni,
    required this.enableUdp,
    required this.enableTcp,
    required this.autoReconnect,
    required this.maxReconnectAttempts,
  });

  String id;
  String name;
  String serverHost;
  int serverPort;
  String transportType;
  String? authToken;
  String deviceId;
  int mtu;
  List<String?> dnsServers;
  String ipv4Address;
  String ipv4SubnetMask;
  List<String?> allowedIPv4Routes;
  List<String?> excludedIPv4Routes;
  int keepAliveSeconds;
  int workers;
  String? sni;
  bool enableUdp;
  bool enableTcp;
  bool autoReconnect;
  int maxReconnectAttempts;

  Object encode() {
    return <Object?>[
      id,
      name,
      serverHost,
      serverPort,
      transportType,
      authToken,
      deviceId,
      mtu,
      dnsServers,
      ipv4Address,
      ipv4SubnetMask,
      allowedIPv4Routes,
      excludedIPv4Routes,
      keepAliveSeconds,
      workers,
      sni,
      enableUdp,
      enableTcp,
      autoReconnect,
      maxReconnectAttempts,
    ];
  }

  static TunnelConfigDto decode(Object result) {
    result as List<Object?>;
    return TunnelConfigDto(
      id: result[0]! as String,
      name: result[1]! as String,
      serverHost: result[2]! as String,
      serverPort: result[3]! as int,
      transportType: result[4]! as String,
      authToken: result[5] as String?,
      deviceId: result[6]! as String,
      mtu: result[7]! as int,
      dnsServers: (result[8] as List<Object?>).cast<String?>(),
      ipv4Address: result[9]! as String,
      ipv4SubnetMask: result[10]! as String,
      allowedIPv4Routes: (result[11] as List<Object?>).cast<String?>(),
      excludedIPv4Routes: (result[12] as List<Object?>).cast<String?>(),
      keepAliveSeconds: result[13]! as int,
      workers: result[14]! as int,
      sni: result[15] as String?,
      enableUdp: result[16]! as bool,
      enableTcp: result[17]! as bool,
      autoReconnect: result[18]! as bool,
      maxReconnectAttempts: result[19]! as int,
    );
  }
}

class TunnelStatusDto {
  TunnelStatusDto({
    required this.status,
    this.lastError,
    this.serverHost,
    this.transportType,
    this.uptimeSeconds,
  });

  String status;
  String? lastError;
  String? serverHost;
  String? transportType;
  int? uptimeSeconds;

  Object encode() {
    return <Object?>[status, lastError, serverHost, transportType, uptimeSeconds];
  }

  static TunnelStatusDto decode(Object result) {
    result as List<Object?>;
    return TunnelStatusDto(
      status: result[0]! as String,
      lastError: result[1] as String?,
      serverHost: result[2] as String?,
      transportType: result[3] as String?,
      uptimeSeconds: result[4] as int?,
    );
  }
}

class TrafficStatsDto {
  TrafficStatsDto({
    required this.bytesIn,
    required this.bytesOut,
    required this.packetsIn,
    required this.packetsOut,
    required this.activeStreams,
    required this.updatedAtMs,
  });

  int bytesIn;
  int bytesOut;
  int packetsIn;
  int packetsOut;
  int activeStreams;
  int updatedAtMs;

  Object encode() {
    return <Object?>[bytesIn, bytesOut, packetsIn, packetsOut, activeStreams, updatedAtMs];
  }

  static TrafficStatsDto decode(Object result) {
    result as List<Object?>;
    return TrafficStatsDto(
      bytesIn: result[0]! as int,
      bytesOut: result[1]! as int,
      packetsIn: result[2]! as int,
      packetsOut: result[3]! as int,
      activeStreams: result[4]! as int,
      updatedAtMs: result[5]! as int,
    );
  }
}

class LogEntryDto {
  LogEntryDto({
    required this.id,
    required this.timestampMs,
    required this.level,
    required this.category,
    required this.message,
    required this.repeatCount,
  });

  String id;
  int timestampMs;
  String level;
  String category;
  String message;
  int repeatCount;

  Object encode() {
    return <Object?>[id, timestampMs, level, category, message, repeatCount];
  }

  static LogEntryDto decode(Object result) {
    result as List<Object?>;
    return LogEntryDto(
      id: result[0]! as String,
      timestampMs: result[1]! as int,
      level: result[2]! as String,
      category: result[3]! as String,
      message: result[4]! as String,
      repeatCount: result[5]! as int,
    );
  }
}

class DiagnosticsDto {
  DiagnosticsDto({
    required this.platform,
    required this.appVersion,
    required this.buildNumber,
    required this.osVersion,
    required this.deviceModel,
    required this.vpnPermissionGranted,
    required this.networkExtensionStatus,
    required this.runnerBundleId,
    required this.extensionBundleId,
    required this.appGroupId,
    required this.goClientVersion,
    required this.keychainAccessGroup,
  });

  String platform;
  String appVersion;
  String buildNumber;
  String osVersion;
  String deviceModel;
  bool vpnPermissionGranted;
  String networkExtensionStatus;
  String runnerBundleId;
  String extensionBundleId;
  String appGroupId;
  String goClientVersion;
  String keychainAccessGroup;

  Object encode() {
    return <Object?>[
      platform,
      appVersion,
      buildNumber,
      osVersion,
      deviceModel,
      vpnPermissionGranted,
      networkExtensionStatus,
      runnerBundleId,
      extensionBundleId,
      appGroupId,
      goClientVersion,
      keychainAccessGroup,
    ];
  }

  static DiagnosticsDto decode(Object result) {
    result as List<Object?>;
    return DiagnosticsDto(
      platform: result[0]! as String,
      appVersion: result[1]! as String,
      buildNumber: result[2]! as String,
      osVersion: result[3]! as String,
      deviceModel: result[4]! as String,
      vpnPermissionGranted: result[5]! as bool,
      networkExtensionStatus: result[6]! as String,
      runnerBundleId: result[7]! as String,
      extensionBundleId: result[8]! as String,
      appGroupId: result[9]! as String,
      goClientVersion: result[10]! as String,
      keychainAccessGroup: result[11]! as String,
    );
  }
}

// ─────────────────────────────────────────────
// AppInfoDto (app exclusions / split tunnel)
// ─────────────────────────────────────────────

class AppInfoDto {
  AppInfoDto({
    required this.packageName,
    required this.label,
    required this.iconBase64,
    required this.isExcluded,
    required this.isWhitelist,
  });

  String packageName;
  String label;
  String iconBase64;
  bool isExcluded;
  bool isWhitelist;

  Object encode() {
    return <Object?>[packageName, label, iconBase64, isExcluded, isWhitelist];
  }

  static AppInfoDto decode(Object result) {
    result as List<Object?>;
    return AppInfoDto(
      packageName: result[0]! as String,
      label:       result[1]! as String,
      iconBase64:  result[2]! as String,
      isExcluded:  result[3]! as bool,
      isWhitelist: result[4]! as bool,
    );
  }
}

// ─────────────────────────────────────────────
// Pigeon codec
// ─────────────────────────────────────────────

class _VpnApiCodec extends StandardMessageCodec {
  const _VpnApiCodec();

  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is TunnelConfigDto) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is TunnelStatusDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is TrafficStatsDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is LogEntryDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is DiagnosticsDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is AppInfoDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return TunnelConfigDto.decode(readValue(buffer)!);
      case 129:
        return TunnelStatusDto.decode(readValue(buffer)!);
      case 130:
        return TrafficStatsDto.decode(readValue(buffer)!);
      case 131:
        return LogEntryDto.decode(readValue(buffer)!);
      case 132:
        return DiagnosticsDto.decode(readValue(buffer)!);
      case 133:
        return AppInfoDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

// ─────────────────────────────────────────────
// Flutter → Native host API
// ─────────────────────────────────────────────

class VpnHostApi {
  VpnHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : _binaryMessenger = binaryMessenger,
        _messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? _binaryMessenger;
  final String _messageChannelSuffix;

  static const MessageCodec<Object?> codec = _VpnApiCodec();

  Future<bool> prepareVpn() async {
    final String channelName = 'dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.prepareVpn$_messageChannelSuffix';
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
      channelName,
      codec,
      binaryMessenger: _binaryMessenger,
    );
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) throw PlatformException(code: 'channel-error', message: 'Unable to establish connection on channel.');
    if (replyList.length > 1) throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
    return (replyList[0] as bool?)!;
  }

  Future<void> installOrUpdateProfile(TunnelConfigDto config) async {
    final String channelName = 'dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.installOrUpdateProfile$_messageChannelSuffix';
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(channelName, codec, binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(<Object?>[config]) as List<Object?>?;
    if (replyList == null) throw PlatformException(code: 'channel-error', message: 'Unable to establish connection on channel.');
    if (replyList.length > 1) throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
  }

  Future<void> startTunnel() async {
    final String channelName = 'dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.startTunnel$_messageChannelSuffix';
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(channelName, codec, binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) throw PlatformException(code: 'channel-error', message: 'Unable to establish connection on channel.');
    if (replyList.length > 1) throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
  }

  Future<void> stopTunnel() async {
    final String channelName = 'dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.stopTunnel$_messageChannelSuffix';
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(channelName, codec, binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) throw PlatformException(code: 'channel-error', message: 'Unable to establish connection on channel.');
    if (replyList.length > 1) throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
  }

  Future<TunnelStatusDto> getStatus() async {
    final String channelName = 'dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.getStatus$_messageChannelSuffix';
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(channelName, codec, binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) throw PlatformException(code: 'channel-error', message: 'Unable to establish connection on channel.');
    if (replyList.length > 1) throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
    return (replyList[0] as TunnelStatusDto?)!;
  }

  Future<TrafficStatsDto> getStats() async {
    final String channelName = 'dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.getStats$_messageChannelSuffix';
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(channelName, codec, binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) throw PlatformException(code: 'channel-error', message: 'Unable to establish connection on channel.');
    if (replyList.length > 1) throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
    return (replyList[0] as TrafficStatsDto?)!;
  }

  Future<List<LogEntryDto?>> getLogs() async {
    final String channelName = 'dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.getLogs$_messageChannelSuffix';
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(channelName, codec, binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) throw PlatformException(code: 'channel-error', message: 'Unable to establish connection on channel.');
    if (replyList.length > 1) throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
    return (replyList[0] as List<Object?>?)!.cast<LogEntryDto?>();
  }

  Future<void> clearLogs() async {
    final String channelName = 'dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.clearLogs$_messageChannelSuffix';
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(channelName, codec, binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) throw PlatformException(code: 'channel-error', message: 'Unable to establish connection on channel.');
    if (replyList.length > 1) throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
  }

  Future<DiagnosticsDto> getDiagnostics() async {
    final String channelName = 'dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.getDiagnostics$_messageChannelSuffix';
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(channelName, codec, binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) throw PlatformException(code: 'channel-error', message: 'Unable to establish connection on channel.');
    if (replyList.length > 1) throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
    return (replyList[0] as DiagnosticsDto?)!;
  }

  Future<void> sendProviderMessage(String type, Map<String, Object?> payload) async {
    final String channelName = 'dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.sendProviderMessage$_messageChannelSuffix';
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(channelName, codec, binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(<Object?>[type, payload]) as List<Object?>?;
    if (replyList == null) throw PlatformException(code: 'channel-error', message: 'Unable to establish connection on channel.');
    if (replyList.length > 1) throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
  }

  /// Returns list of installed apps with their current exclusion status.
  /// Android only — returns empty list on iOS.
  Future<List<AppInfoDto?>> getInstalledApps() async {
    final String channelName = 'dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.getInstalledApps$_messageChannelSuffix';
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(channelName, codec, binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(null) as List<Object?>?;
    if (replyList == null) throw PlatformException(code: 'channel-error', message: 'Unable to establish connection on channel.');
    if (replyList.length > 1) throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
    return (replyList[0] as List<Object?>?)!.cast<AppInfoDto?>();
  }

  /// Saves the excluded app list and optionally reloads the WireGuard tunnel.
  Future<void> setExcludedApps(List<String?> packages, bool isWhitelist) async {
    final String channelName = 'dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.setExcludedApps$_messageChannelSuffix';
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(channelName, codec, binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList = await channel.send(<Object?>[packages, isWhitelist]) as List<Object?>?;
    if (replyList == null) throw PlatformException(code: 'channel-error', message: 'Unable to establish connection on channel.');
    if (replyList.length > 1) throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
  }
}

// ─────────────────────────────────────────────
// Native → Flutter callback API
// ─────────────────────────────────────────────

abstract class VpnFlutterApi {
  static const MessageCodec<Object?> codec = _VpnApiCodec();

  void onStatusChanged(TunnelStatusDto status);
  void onStatsChanged(TrafficStatsDto stats);
  void onLogReceived(LogEntryDto entry);

  static void setUp(VpnFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''}) {
    final String suffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_vpn_go.VpnFlutterApi.onStatusChanged$suffix',
        codec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null, 'Argument for dev.flutter.pigeon.flutter_vpn_go.VpnFlutterApi.onStatusChanged was null.');
          final List<Object?> args = (message as List<Object?>);
          final TunnelStatusDto arg_status = (args[0] as TunnelStatusDto?)!;
          api.onStatusChanged(arg_status);
          return <Object?>[];
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_vpn_go.VpnFlutterApi.onStatsChanged$suffix',
        codec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          final List<Object?> args = (message as List<Object?>);
          final TrafficStatsDto arg_stats = (args[0] as TrafficStatsDto?)!;
          api.onStatsChanged(arg_stats);
          return <Object?>[];
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_vpn_go.VpnFlutterApi.onLogReceived$suffix',
        codec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          final List<Object?> args = (message as List<Object?>);
          final LogEntryDto arg_entry = (args[0] as LogEntryDto?)!;
          api.onLogReceived(arg_entry);
          return <Object?>[];
        });
      }
    }
  }
}
