// Autogenerated from Pigeon (v18.x), do not edit directly.
// Source: pigeons/vpn_api.dart
// swiftlint:disable all

import Flutter
import Foundation

private func wrapResult(_ result: Any?) -> [Any?] { [result] }
private func wrapError(_ error: Error) -> [Any?] {
    let flutterError = error as? FlutterError
    return [
        flutterError?.code ?? "\(type(of: error))",
        flutterError?.message ?? error.localizedDescription,
        flutterError?.details,
    ]
}

// ─────────────────────────────────────────────
// DTOs
// ─────────────────────────────────────────────

class TunnelConfigDto: NSObject {
    var id: String
    var name: String
    var serverHost: String
    var serverPort: Int64
    var transportType: String
    var authToken: String?
    var deviceId: String
    var mtu: Int64
    var dnsServers: [String?]
    var ipv4Address: String
    var ipv4SubnetMask: String
    var allowedIPv4Routes: [String?]
    var excludedIPv4Routes: [String?]
    var keepAliveSeconds: Int64
    var workers: Int64
    var sni: String?
    var enableUdp: Bool
    var enableTcp: Bool
    var autoReconnect: Bool
    var maxReconnectAttempts: Int64

    init(id: String, name: String, serverHost: String, serverPort: Int64,
         transportType: String, authToken: String?, deviceId: String, mtu: Int64,
         dnsServers: [String?], ipv4Address: String, ipv4SubnetMask: String,
         allowedIPv4Routes: [String?], excludedIPv4Routes: [String?],
         keepAliveSeconds: Int64, workers: Int64, sni: String?,
         enableUdp: Bool, enableTcp: Bool, autoReconnect: Bool,
         maxReconnectAttempts: Int64) {
        self.id = id; self.name = name; self.serverHost = serverHost
        self.serverPort = serverPort; self.transportType = transportType
        self.authToken = authToken; self.deviceId = deviceId; self.mtu = mtu
        self.dnsServers = dnsServers; self.ipv4Address = ipv4Address
        self.ipv4SubnetMask = ipv4SubnetMask; self.allowedIPv4Routes = allowedIPv4Routes
        self.excludedIPv4Routes = excludedIPv4Routes; self.keepAliveSeconds = keepAliveSeconds
        self.workers = workers; self.sni = sni; self.enableUdp = enableUdp
        self.enableTcp = enableTcp; self.autoReconnect = autoReconnect
        self.maxReconnectAttempts = maxReconnectAttempts
    }

    static func fromList(_ list: [Any?]) -> TunnelConfigDto {
        return TunnelConfigDto(
            id: list[0] as! String, name: list[1] as! String,
            serverHost: list[2] as! String,
            serverPort: Int64(truncatingIfNeeded: list[3] as! NSNumber),
            transportType: list[4] as! String, authToken: list[5] as? String,
            deviceId: list[6] as! String,
            mtu: Int64(truncatingIfNeeded: list[7] as! NSNumber),
            dnsServers: list[8] as! [String?], ipv4Address: list[9] as! String,
            ipv4SubnetMask: list[10] as! String,
            allowedIPv4Routes: list[11] as! [String?],
            excludedIPv4Routes: list[12] as! [String?],
            keepAliveSeconds: Int64(truncatingIfNeeded: list[13] as! NSNumber),
            workers: Int64(truncatingIfNeeded: list[14] as! NSNumber),
            sni: list[15] as? String, enableUdp: list[16] as! Bool,
            enableTcp: list[17] as! Bool, autoReconnect: list[18] as! Bool,
            maxReconnectAttempts: Int64(truncatingIfNeeded: list[19] as! NSNumber)
        )
    }
    func toList() -> [Any?] {
        return [id, name, serverHost, serverPort, transportType, authToken, deviceId, mtu,
                dnsServers, ipv4Address, ipv4SubnetMask, allowedIPv4Routes, excludedIPv4Routes,
                keepAliveSeconds, workers, sni, enableUdp, enableTcp, autoReconnect, maxReconnectAttempts]
    }
}

class TunnelStatusDto: NSObject {
    var status: String; var lastError: String?
    var serverHost: String?; var transportType: String?; var uptimeSeconds: Int64?
    init(status: String, lastError: String? = nil, serverHost: String? = nil,
         transportType: String? = nil, uptimeSeconds: Int64? = nil) {
        self.status = status; self.lastError = lastError
        self.serverHost = serverHost; self.transportType = transportType
        self.uptimeSeconds = uptimeSeconds
    }
    static func fromList(_ list: [Any?]) -> TunnelStatusDto {
        TunnelStatusDto(status: list[0] as! String, lastError: list[1] as? String,
                        serverHost: list[2] as? String, transportType: list[3] as? String,
                        uptimeSeconds: (list[4] as? NSNumber).map { Int64(truncatingIfNeeded: $0) })
    }
    func toList() -> [Any?] { [status, lastError, serverHost, transportType, uptimeSeconds as Any?] }
}

class TrafficStatsDto: NSObject {
    var bytesIn: Int64; var bytesOut: Int64
    var packetsIn: Int64; var packetsOut: Int64
    var activeStreams: Int64; var updatedAtMs: Int64
    init(bytesIn: Int64, bytesOut: Int64, packetsIn: Int64, packetsOut: Int64,
         activeStreams: Int64, updatedAtMs: Int64) {
        self.bytesIn = bytesIn; self.bytesOut = bytesOut
        self.packetsIn = packetsIn; self.packetsOut = packetsOut
        self.activeStreams = activeStreams; self.updatedAtMs = updatedAtMs
    }
    static func fromList(_ list: [Any?]) -> TrafficStatsDto {
        TrafficStatsDto(
            bytesIn: Int64(truncatingIfNeeded: list[0] as! NSNumber),
            bytesOut: Int64(truncatingIfNeeded: list[1] as! NSNumber),
            packetsIn: Int64(truncatingIfNeeded: list[2] as! NSNumber),
            packetsOut: Int64(truncatingIfNeeded: list[3] as! NSNumber),
            activeStreams: Int64(truncatingIfNeeded: list[4] as! NSNumber),
            updatedAtMs: Int64(truncatingIfNeeded: list[5] as! NSNumber))
    }
    func toList() -> [Any?] { [bytesIn, bytesOut, packetsIn, packetsOut, activeStreams, updatedAtMs] }
}

class LogEntryDto: NSObject {
    var id: String; var timestampMs: Int64
    var level: String; var category: String; var message: String; var repeatCount: Int64
    init(id: String, timestampMs: Int64, level: String, category: String, message: String, repeatCount: Int64) {
        self.id = id; self.timestampMs = timestampMs; self.level = level
        self.category = category; self.message = message; self.repeatCount = repeatCount
    }
    static func fromList(_ list: [Any?]) -> LogEntryDto {
        LogEntryDto(id: list[0] as! String,
                    timestampMs: Int64(truncatingIfNeeded: list[1] as! NSNumber),
                    level: list[2] as! String, category: list[3] as! String,
                    message: list[4] as! String,
                    repeatCount: Int64(truncatingIfNeeded: list[5] as! NSNumber))
    }
    func toList() -> [Any?] { [id, timestampMs, level, category, message, repeatCount] }
}

class DiagnosticsDto: NSObject {
    var platform: String; var appVersion: String; var buildNumber: String
    var osVersion: String; var deviceModel: String; var vpnPermissionGranted: Bool
    var networkExtensionStatus: String; var runnerBundleId: String
    var extensionBundleId: String; var appGroupId: String
    var goClientVersion: String; var keychainAccessGroup: String
    init(platform: String, appVersion: String, buildNumber: String, osVersion: String,
         deviceModel: String, vpnPermissionGranted: Bool, networkExtensionStatus: String,
         runnerBundleId: String, extensionBundleId: String, appGroupId: String,
         goClientVersion: String, keychainAccessGroup: String) {
        self.platform = platform; self.appVersion = appVersion; self.buildNumber = buildNumber
        self.osVersion = osVersion; self.deviceModel = deviceModel
        self.vpnPermissionGranted = vpnPermissionGranted
        self.networkExtensionStatus = networkExtensionStatus; self.runnerBundleId = runnerBundleId
        self.extensionBundleId = extensionBundleId; self.appGroupId = appGroupId
        self.goClientVersion = goClientVersion; self.keychainAccessGroup = keychainAccessGroup
    }
    func toList() -> [Any?] {
        [platform, appVersion, buildNumber, osVersion, deviceModel, vpnPermissionGranted,
         networkExtensionStatus, runnerBundleId, extensionBundleId, appGroupId,
         goClientVersion, keychainAccessGroup]
    }
}

// ─────────────────────────────────────────────
// Pigeon codec
// ─────────────────────────────────────────────

private class VpnApiCodec: FlutterStandardMessageCodec {
    static let shared = VpnApiCodec(readerWriter: VpnApiCodecReaderWriter())
}
private class VpnApiCodecReaderWriter: FlutterStandardReaderWriter {
    override func reader(with data: Data) -> FlutterStandardReader { VpnApiCodecReader(data: data) }
    override func writer(with data: NSMutableData) -> FlutterStandardWriter { VpnApiCodecWriter(data: data) }
}
private class VpnApiCodecReader: FlutterStandardReader {
    override func readValue(ofType type: UInt8) -> Any? {
        switch type {
        case 128: return TunnelConfigDto.fromList(self.readValue() as! [Any?])
        case 129: return TunnelStatusDto.fromList(self.readValue() as! [Any?])
        case 130: return TrafficStatsDto.fromList(self.readValue() as! [Any?])
        case 131: return LogEntryDto.fromList(self.readValue() as! [Any?])
        case 132: return DiagnosticsDto.fromList(self.readValue() as! [Any?])
        default:  return super.readValue(ofType: type)
        }
    }
}
private class VpnApiCodecWriter: FlutterStandardWriter {
    override func writeValue(_ value: Any) {
        if let v = value as? TunnelConfigDto  { writeByte(128); writeValue(v.toList()) }
        else if let v = value as? TunnelStatusDto  { writeByte(129); writeValue(v.toList()) }
        else if let v = value as? TrafficStatsDto  { writeByte(130); writeValue(v.toList()) }
        else if let v = value as? LogEntryDto      { writeByte(131); writeValue(v.toList()) }
        else if let v = value as? DiagnosticsDto   { writeByte(132); writeValue(v.toList()) }
        else { super.writeValue(value) }
    }
}

// ─────────────────────────────────────────────
// Flutter → Native host API
// ─────────────────────────────────────────────

protocol VpnHostApiProtocol {
    func prepareVpn(completion: @escaping (Result<Bool, Error>) -> Void)
    func installOrUpdateProfile(config: TunnelConfigDto, completion: @escaping (Result<Void, Error>) -> Void)
    func startTunnel(completion: @escaping (Result<Void, Error>) -> Void)
    func stopTunnel(completion: @escaping (Result<Void, Error>) -> Void)
    func getStatus(completion: @escaping (Result<TunnelStatusDto, Error>) -> Void)
    func getStats(completion: @escaping (Result<TrafficStatsDto, Error>) -> Void)
    func getLogs(completion: @escaping (Result<[LogEntryDto?], Error>) -> Void)
    func clearLogs(completion: @escaping (Result<Void, Error>) -> Void)
    func getDiagnostics(completion: @escaping (Result<DiagnosticsDto, Error>) -> Void)
    func sendProviderMessage(type: String, payload: [String: Any?], completion: @escaping (Result<Void, Error>) -> Void)
}

class VpnHostApiSetup {
    private static let codec = VpnApiCodec.shared

    static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VpnHostApiProtocol?) {
        let suffix = ""

        makeChannel("prepareVpn", binaryMessenger, suffix) { _, reply in
            guard let api = api else { reply(nil); return }
            api.prepareVpn { result in
                switch result {
                case .success(let v): reply(wrapResult(v))
                case .failure(let e): reply(wrapError(e))
                }
            }
        }
        makeChannel("installOrUpdateProfile", binaryMessenger, suffix) { msg, reply in
            guard let api = api, let args = msg as? [Any?] else { reply(nil); return }
            let config = TunnelConfigDto.fromList(args[0] as! [Any?])
            api.installOrUpdateProfile(config: config) { result in
                switch result {
                case .success: reply(wrapResult(nil))
                case .failure(let e): reply(wrapError(e))
                }
            }
        }
        makeChannel("startTunnel", binaryMessenger, suffix) { _, reply in
            guard let api = api else { reply(nil); return }
            api.startTunnel { result in
                switch result {
                case .success: reply(wrapResult(nil))
                case .failure(let e): reply(wrapError(e))
                }
            }
        }
        makeChannel("stopTunnel", binaryMessenger, suffix) { _, reply in
            guard let api = api else { reply(nil); return }
            api.stopTunnel { result in
                switch result {
                case .success: reply(wrapResult(nil))
                case .failure(let e): reply(wrapError(e))
                }
            }
        }
        makeChannel("getStatus", binaryMessenger, suffix) { _, reply in
            guard let api = api else { reply(nil); return }
            api.getStatus { result in
                switch result {
                case .success(let v): reply(wrapResult(v))
                case .failure(let e): reply(wrapError(e))
                }
            }
        }
        makeChannel("getStats", binaryMessenger, suffix) { _, reply in
            guard let api = api else { reply(nil); return }
            api.getStats { result in
                switch result {
                case .success(let v): reply(wrapResult(v))
                case .failure(let e): reply(wrapError(e))
                }
            }
        }
        makeChannel("getLogs", binaryMessenger, suffix) { _, reply in
            guard let api = api else { reply(nil); return }
            api.getLogs { result in
                switch result {
                case .success(let v): reply(wrapResult(v))
                case .failure(let e): reply(wrapError(e))
                }
            }
        }
        makeChannel("clearLogs", binaryMessenger, suffix) { _, reply in
            guard let api = api else { reply(nil); return }
            api.clearLogs { result in
                switch result {
                case .success: reply(wrapResult(nil))
                case .failure(let e): reply(wrapError(e))
                }
            }
        }
        makeChannel("getDiagnostics", binaryMessenger, suffix) { _, reply in
            guard let api = api else { reply(nil); return }
            api.getDiagnostics { result in
                switch result {
                case .success(let v): reply(wrapResult(v))
                case .failure(let e): reply(wrapError(e))
                }
            }
        }
        makeChannel("sendProviderMessage", binaryMessenger, suffix) { msg, reply in
            guard let api = api, let args = msg as? [Any?] else { reply(nil); return }
            let typeArg = args[0] as! String
            let payloadArg = args[1] as! [String: Any?]
            api.sendProviderMessage(type: typeArg, payload: payloadArg) { result in
                switch result {
                case .success: reply(wrapResult(nil))
                case .failure(let e): reply(wrapError(e))
                }
            }
        }
    }

    private static func makeChannel(
        _ method: String,
        _ messenger: FlutterBinaryMessenger,
        _ suffix: String,
        handler: @escaping (Any?, @escaping FlutterReply) -> Void
    ) {
        let name = "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.\(method)\(suffix)"
        let ch = FlutterBasicMessageChannel(name: name, binaryMessenger: messenger, codec: codec)
        ch.setMessageHandler(handler)
    }
}
