import Foundation
import GoClient  // generated by: gomobile bind -target=ios ./client

/// Wraps the gomobile-generated Objective-C/Swift API for the Go VPN client.
///
/// Usage inside PacketTunnelProvider:
///   let bridge = GoClientBridge()
///   bridge.setLogger(logger)
///   try bridge.start(configJSON: configJSON)
///   // packet loop:
///   try bridge.writePacket(data, proto: 4)
///   let pkt = try bridge.readPacket()
///   // teardown:
///   bridge.stop()
class GoClientBridge {

    private let goClient: ClientClient   // gomobile generates "Client" class → prefixed with module name

    init() {
        goClient = ClientNewClient()!    // gomobile: func NewClient() *Client → ClientNewClient()
    }

    // ── Logger ─────────────────────────────────────────────────────────────

    func setLogger(_ logger: GoLoggerBridge) {
        goClient.setLogger(logger)
    }

    // ── Lifecycle ──────────────────────────────────────────────────────────

    func start(configJSON: String) throws {
        var err: NSError?
        goClient.start(configJSON, error: &err)
        if let err = err { throw err }
    }

    func stop() {
        _ = try? goClient.stop()
    }

    // ── Packet I/O ─────────────────────────────────────────────────────────

    /// Write outbound IP packet to Go transport.
    /// proto: 4 = IPv4, 6 = IPv6.
    func writePacket(_ data: Data, proto: Int) throws {
        var err: NSError?
        goClient.writePacket(data, proto: proto, error: &err)
        if let err = err { throw err }
    }

    /// Read next inbound IP packet from Go transport.
    /// Blocks until a packet is available.
    func readPacket() throws -> Data {
        var err: NSError?
        guard let data = goClient.readPacket(&err) else {
            throw err ?? NSError(domain: "GoClientBridge", code: -1,
                                 userInfo: [NSLocalizedDescriptionKey: "readPacket returned nil"])
        }
        return data
    }

    // ── Status & Stats ─────────────────────────────────────────────────────

    func status() -> String {
        goClient.status() ?? "disconnected"
    }

    func statsJSON() -> String {
        goClient.statsJSON() ?? "{}"
    }

    func version() -> String {
        ClientVersion() ?? "unknown"   // gomobile: func Version() string → ClientVersion()
    }
}

// ── Go Logger bridge ──────────────────────────────────────────────────────

/// Implements the gomobile-generated Logger protocol so Swift can receive Go logs.
class GoLoggerBridge: NSObject, ClientLoggerProtocol {
    let tunnelLogger: TunnelLogger

    init(tunnelLogger: TunnelLogger) {
        self.tunnelLogger = tunnelLogger
    }

    /// Called by Go client for every log entry.
    func log(_ level: String?, category: String?, message: String?) {
        tunnelLogger.log(
            level: level ?? "info",
            category: category ?? "go",
            message: message ?? ""
        )
    }
}
