package com.example.fluttervpngo.vpnplugin

import android.util.Log
import client.Logger  // generated by gomobile
import java.util.UUID
import java.util.concurrent.ConcurrentLinkedDeque

/**
 * Bridges Go client Logger interface to Android Logcat and an in-memory buffer.
 * The buffer is drained by FlutterVpnPlugin on Flutter polling requests.
 *
 * This class is passed to GoClientBridge.setLogger() and implements the
 * gomobile-generated Logger interface from the Go client package.
 */
class AndroidLogBridge : Logger {

    private val buffer = ConcurrentLinkedDeque<LogEntryData>()
    private val maxBuffer = 1000

    data class LogEntryData(
        val id: String,
        val timestampMs: Long,
        val level: String,
        val category: String,
        val message: String,
        var repeatCount: Int = 1,
    )

    override fun log(level: String, category: String, message: String) {
        val androidLevel = when (level.lowercase()) {
            "debug"   -> Log.DEBUG
            "warning" -> Log.WARN
            "error"   -> Log.ERROR
            else      -> Log.INFO
        }
        Log.println(androidLevel, "VpnGo/$category", message)

        // Group repeated messages
        val last = buffer.peekLast()
        if (last != null && last.level == level && last.category == category && last.message == message) {
            last.repeatCount++
            return
        }

        if (buffer.size >= maxBuffer) buffer.pollFirst()

        buffer.addLast(
            LogEntryData(
                id          = UUID.randomUUID().toString(),
                timestampMs = System.currentTimeMillis(),
                level       = level,
                category    = category,
                message     = message,
            )
        )
    }

    /** Drains the buffer and returns all pending entries. */
    fun drainAll(): List<LogEntryData> {
        val result = mutableListOf<LogEntryData>()
        while (buffer.isNotEmpty()) {
            result.add(buffer.pollFirst() ?: break)
        }
        return result
    }

    fun clear() = buffer.clear()
}
