package com.example.fluttervpngo.vpnplugin

import android.util.Log
// gomobile bind generates a Java/Kotlin package named after the Go package.
// For package "client", the class is "client.Client" and the static func
// Version() becomes "client.Client.version()" or top-level "client.ClientKt".
// Adjust import paths after running: gomobile bind ./client
import client.Client   // generated by: gomobile bind -target=android ./client

/**
 * Wraps the gomobile-generated Go client API.
 *
 * Lifecycle:
 *   1. GoClientBridge.instance.setLogger(logBridge)
 *   2. GoClientBridge.instance.start(configJSON)
 *   3. Native TUN loop calls writePacket() / readPacket() on a background thread
 *   4. GoClientBridge.instance.stop()
 *
 * NOTE: The exact class name depends on the Go package name.
 * For "package client", gomobile generates class "client.Client".
 * The top-level func Version() is accessed as Client.version() via a static shim,
 * or via the generated package-level function.
 */
class GoClientBridge private constructor() {

    companion object {
        val instance: GoClientBridge by lazy { GoClientBridge() }
        private const val TAG = "GoClientBridge"
    }

    // gomobile: NewClient() *Client → client.Client.newClient() factory or direct constructor
    private val goClient: Client = Client()
    private var logBridge: AndroidLogBridge? = null

    // ── Logger ────────────────────────────────────────────────────────────

    fun setLogger(bridge: AndroidLogBridge) {
        logBridge = bridge
        goClient.setLogger(bridge)
    }

    // ── Lifecycle ──────────────────────────────────────────────────────────

    /**
     * Start the Go VPN client.
     * @param configJSON Full TunnelConfig JSON from Flutter (authToken included).
     * @throws Exception if Go returns an error.
     */
    fun start(configJSON: String) {
        Log.d(TAG, "start() called")
        val err = goClient.start(configJSON)
        if (err != null) {
            throw Exception("GoClient start failed: $err")
        }
    }

    fun stop() {
        Log.d(TAG, "stop() called")
        val err = goClient.stop()
        if (err != null) {
            Log.w(TAG, "GoClient stop error: $err")
        }
    }

    // ── Packet I/O (called from TunDeviceBridge on background threads) ────

    /**
     * Write an outbound IP packet to the Go transport.
     * @param packet  Raw IP packet bytes.
     * @param proto   4 = IPv4, 6 = IPv6.
     */
    fun writePacket(packet: ByteArray, proto: Int) {
        try {
            // gomobile maps Go `int` to Java `long`
            goClient.writePacket(packet, proto.toLong())
        } catch (e: Exception) {
            Log.w(TAG, "writePacket error: ${e.message}")
        }
    }

    /**
     * Read the next inbound IP packet from the Go transport.
     * Blocks until a packet is available or the client is stopped.
     * @return Packet bytes, or null if the client has been stopped.
     */
    fun readPacket(): ByteArray? {
        return try {
            goClient.readPacket()
        } catch (e: Exception) {
            Log.w(TAG, "readPacket error: ${e.message}")
            null
        }
    }

    // ── Status & Stats ────────────────────────────────────────────────────

    fun status(): String = goClient.status() ?: "disconnected"

    fun statsJSON(): String =
        goClient.statsJSON() ?: """{"bytesIn":0,"bytesOut":0,"packetsIn":0,"packetsOut":0,"activeStreams":0}"""

    // gomobile generates a top-level Version() func as a static method on the package class.
    // Exact generated name: client.Client.version() — adjust if gomobile renames it.
    fun version(): String = try {
        // Reflection fallback in case gomobile naming differs
        val method = Client::class.java.getMethod("version")
        method.invoke(null) as? String ?: "unknown"
    } catch (_: Exception) {
        "unknown"
    }
}
