// Autogenerated from Pigeon (v18.x), do not edit directly.
// Source: pigeons/vpn_api.dart
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass", "unused", "RemoveRedundantQualifierName")

package com.example.fluttervpngo.vpnplugin

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> = listOf(result)
private fun wrapError(exception: Throwable): List<Any?> = listOf(
    exception.javaClass.simpleName,
    exception.message,
    exception.toString(),
)

// ─────────────────────────────────────────────
// DTOs
// ─────────────────────────────────────────────

data class TunnelConfigDto(
    val id: String,
    val name: String,
    val serverHost: String,
    val serverPort: Long,
    val transportType: String,
    val authToken: String?,
    val deviceId: String,
    val mtu: Long,
    val dnsServers: List<String?>,
    val ipv4Address: String,
    val ipv4SubnetMask: String,
    val allowedIPv4Routes: List<String?>,
    val excludedIPv4Routes: List<String?>,
    val keepAliveSeconds: Long,
    val workers: Long,
    val sni: String?,
    val enableUdp: Boolean,
    val enableTcp: Boolean,
    val autoReconnect: Boolean,
    val maxReconnectAttempts: Long,
) {
    companion object {
        fun fromList(list: List<Any?>): TunnelConfigDto = TunnelConfigDto(
            id                   = list[0] as String,
            name                 = list[1] as String,
            serverHost           = list[2] as String,
            serverPort           = list[3].let { if (it is Int) it.toLong() else it as Long },
            transportType        = list[4] as String,
            authToken            = list[5] as String?,
            deviceId             = list[6] as String,
            mtu                  = list[7].let { if (it is Int) it.toLong() else it as Long },
            dnsServers           = list[8] as List<String?>,
            ipv4Address          = list[9] as String,
            ipv4SubnetMask       = list[10] as String,
            allowedIPv4Routes    = list[11] as List<String?>,
            excludedIPv4Routes   = list[12] as List<String?>,
            keepAliveSeconds     = list[13].let { if (it is Int) it.toLong() else it as Long },
            workers              = list[14].let { if (it is Int) it.toLong() else it as Long },
            sni                  = list[15] as String?,
            enableUdp            = list[16] as Boolean,
            enableTcp            = list[17] as Boolean,
            autoReconnect        = list[18] as Boolean,
            maxReconnectAttempts = list[19].let { if (it is Int) it.toLong() else it as Long },
        )
    }
    fun toList(): List<Any?> = listOf(id, name, serverHost, serverPort, transportType, authToken,
        deviceId, mtu, dnsServers, ipv4Address, ipv4SubnetMask, allowedIPv4Routes,
        excludedIPv4Routes, keepAliveSeconds, workers, sni, enableUdp, enableTcp,
        autoReconnect, maxReconnectAttempts)
}

data class TunnelStatusDto(
    val status: String,
    val lastError: String?,
    val serverHost: String?,
    val transportType: String?,
    val uptimeSeconds: Long?,
) {
    companion object {
        fun fromList(list: List<Any?>): TunnelStatusDto = TunnelStatusDto(
            status        = list[0] as String,
            lastError     = list[1] as String?,
            serverHost    = list[2] as String?,
            transportType = list[3] as String?,
            uptimeSeconds = list[4]?.let { if (it is Int) it.toLong() else it as Long },
        )
    }
    fun toList(): List<Any?> = listOf(status, lastError, serverHost, transportType, uptimeSeconds)
}

data class TrafficStatsDto(
    val bytesIn: Long,
    val bytesOut: Long,
    val packetsIn: Long,
    val packetsOut: Long,
    val activeStreams: Long,
    val updatedAtMs: Long,
) {
    companion object {
        fun fromList(list: List<Any?>): TrafficStatsDto = TrafficStatsDto(
            bytesIn       = list[0].let { if (it is Int) it.toLong() else it as Long },
            bytesOut      = list[1].let { if (it is Int) it.toLong() else it as Long },
            packetsIn     = list[2].let { if (it is Int) it.toLong() else it as Long },
            packetsOut    = list[3].let { if (it is Int) it.toLong() else it as Long },
            activeStreams  = list[4].let { if (it is Int) it.toLong() else it as Long },
            updatedAtMs   = list[5].let { if (it is Int) it.toLong() else it as Long },
        )
    }
    fun toList(): List<Any?> = listOf(bytesIn, bytesOut, packetsIn, packetsOut, activeStreams, updatedAtMs)
}

data class LogEntryDto(
    val id: String,
    val timestampMs: Long,
    val level: String,
    val category: String,
    val message: String,
    val repeatCount: Long,
) {
    companion object {
        fun fromList(list: List<Any?>): LogEntryDto = LogEntryDto(
            id          = list[0] as String,
            timestampMs = list[1].let { if (it is Int) it.toLong() else it as Long },
            level       = list[2] as String,
            category    = list[3] as String,
            message     = list[4] as String,
            repeatCount = list[5].let { if (it is Int) it.toLong() else it as Long },
        )
    }
    fun toList(): List<Any?> = listOf(id, timestampMs, level, category, message, repeatCount)
}

data class DiagnosticsDto(
    val platform: String,
    val appVersion: String,
    val buildNumber: String,
    val osVersion: String,
    val deviceModel: String,
    val vpnPermissionGranted: Boolean,
    val networkExtensionStatus: String,
    val runnerBundleId: String,
    val extensionBundleId: String,
    val appGroupId: String,
    val goClientVersion: String,
    val keychainAccessGroup: String,
) {
    companion object {
        fun fromList(list: List<Any?>): DiagnosticsDto = DiagnosticsDto(
            platform               = list[0] as String,
            appVersion             = list[1] as String,
            buildNumber            = list[2] as String,
            osVersion              = list[3] as String,
            deviceModel            = list[4] as String,
            vpnPermissionGranted   = list[5] as Boolean,
            networkExtensionStatus = list[6] as String,
            runnerBundleId         = list[7] as String,
            extensionBundleId      = list[8] as String,
            appGroupId             = list[9] as String,
            goClientVersion        = list[10] as String,
            keychainAccessGroup    = list[11] as String,
        )
    }
    fun toList(): List<Any?> = listOf(platform, appVersion, buildNumber, osVersion, deviceModel,
        vpnPermissionGranted, networkExtensionStatus, runnerBundleId, extensionBundleId,
        appGroupId, goClientVersion, keychainAccessGroup)
}

// ─────────────────────────────────────────────
// AppInfoDto (app exclusions)
// ─────────────────────────────────────────────

data class AppInfoDto(
    val packageName: String,
    val label: String,
    val iconBase64: String,
    val isExcluded: Boolean,
    val isWhitelist: Boolean,
) {
    companion object {
        fun fromList(list: List<Any?>): AppInfoDto = AppInfoDto(
            packageName = list[0] as String,
            label       = list[1] as String,
            iconBase64  = list[2] as String,
            isExcluded  = list[3] as Boolean,
            isWhitelist = list[4] as Boolean,
        )
    }
    fun toList(): List<Any?> = listOf(packageName, label, iconBase64, isExcluded, isWhitelist)
}

// ─────────────────────────────────────────────
// Pigeon codec
// ─────────────────────────────────────────────

private object VpnApiCodec : StandardMessageCodec() {
    override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? = when (type) {
        128.toByte() -> TunnelConfigDto.fromList(readValue(buffer) as List<Any?>)
        129.toByte() -> TunnelStatusDto.fromList(readValue(buffer) as List<Any?>)
        130.toByte() -> TrafficStatsDto.fromList(readValue(buffer) as List<Any?>)
        131.toByte() -> LogEntryDto.fromList(readValue(buffer) as List<Any?>)
        132.toByte() -> DiagnosticsDto.fromList(readValue(buffer) as List<Any?>)
        133.toByte() -> AppInfoDto.fromList(readValue(buffer) as List<Any?>)
        else         -> super.readValueOfType(type, buffer)
    }
    override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
        when (value) {
            is TunnelConfigDto  -> { stream.write(128); writeValue(stream, value.toList()) }
            is TunnelStatusDto  -> { stream.write(129); writeValue(stream, value.toList()) }
            is TrafficStatsDto  -> { stream.write(130); writeValue(stream, value.toList()) }
            is LogEntryDto      -> { stream.write(131); writeValue(stream, value.toList()) }
            is DiagnosticsDto   -> { stream.write(132); writeValue(stream, value.toList()) }
            is AppInfoDto       -> { stream.write(133); writeValue(stream, value.toList()) }
            else                -> super.writeValue(stream, value)
        }
    }
}

// ─────────────────────────────────────────────
// Flutter → Native host API
// ─────────────────────────────────────────────

interface VpnHostApi {
    fun prepareVpn(callback: (Result<Boolean>) -> Unit)
    fun installOrUpdateProfile(config: TunnelConfigDto, callback: (Result<Unit>) -> Unit)
    fun startTunnel(callback: (Result<Unit>) -> Unit)
    fun stopTunnel(callback: (Result<Unit>) -> Unit)
    fun getStatus(callback: (Result<TunnelStatusDto>) -> Unit)
    fun getStats(callback: (Result<TrafficStatsDto>) -> Unit)
    fun getLogs(callback: (Result<List<LogEntryDto?>>) -> Unit)
    fun clearLogs(callback: (Result<Unit>) -> Unit)
    fun getDiagnostics(callback: (Result<DiagnosticsDto>) -> Unit)
    fun sendProviderMessage(type: String, payload: Map<String, Any?>, callback: (Result<Unit>) -> Unit)
    // App exclusions (split tunnel)
    fun getInstalledApps(callback: (Result<List<AppInfoDto?>>) -> Unit)
    fun setExcludedApps(packages: List<String?>, isWhitelist: Boolean, callback: (Result<Unit>) -> Unit)

    companion object {
        private const val TAG = "VpnHostApi"
        private val codec: MessageCodec<Any?> = VpnApiCodec

        fun setUp(binaryMessenger: BinaryMessenger, api: VpnHostApi?) {
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger, "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.prepareVpn", codec)
                if (api == null) channel.setMessageHandler(null)
                else channel.setMessageHandler { _, reply ->
                    api.prepareVpn { result ->
                        result.fold(
                            { reply.reply(wrapResult(it)) },
                            { reply.reply(wrapError(it)) },
                        )
                    }
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger, "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.installOrUpdateProfile", codec)
                if (api == null) channel.setMessageHandler(null)
                else channel.setMessageHandler { message, reply ->
                    val args = message as List<Any?>
                    val configArg = TunnelConfigDto.fromList(args[0] as List<Any?>)
                    api.installOrUpdateProfile(configArg) { result ->
                        result.fold({ reply.reply(wrapResult(null)) }, { reply.reply(wrapError(it)) })
                    }
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger, "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.startTunnel", codec)
                if (api == null) channel.setMessageHandler(null)
                else channel.setMessageHandler { _, reply ->
                    api.startTunnel { result ->
                        result.fold({ reply.reply(wrapResult(null)) }, { reply.reply(wrapError(it)) })
                    }
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger, "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.stopTunnel", codec)
                if (api == null) channel.setMessageHandler(null)
                else channel.setMessageHandler { _, reply ->
                    api.stopTunnel { result ->
                        result.fold({ reply.reply(wrapResult(null)) }, { reply.reply(wrapError(it)) })
                    }
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger, "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.getStatus", codec)
                if (api == null) channel.setMessageHandler(null)
                else channel.setMessageHandler { _, reply ->
                    api.getStatus { result ->
                        result.fold({ reply.reply(wrapResult(it)) }, { reply.reply(wrapError(it)) })
                    }
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger, "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.getStats", codec)
                if (api == null) channel.setMessageHandler(null)
                else channel.setMessageHandler { _, reply ->
                    api.getStats { result ->
                        result.fold({ reply.reply(wrapResult(it)) }, { reply.reply(wrapError(it)) })
                    }
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger, "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.getLogs", codec)
                if (api == null) channel.setMessageHandler(null)
                else channel.setMessageHandler { _, reply ->
                    api.getLogs { result ->
                        result.fold({ reply.reply(wrapResult(it)) }, { reply.reply(wrapError(it)) })
                    }
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger, "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.clearLogs", codec)
                if (api == null) channel.setMessageHandler(null)
                else channel.setMessageHandler { _, reply ->
                    api.clearLogs { result ->
                        result.fold({ reply.reply(wrapResult(null)) }, { reply.reply(wrapError(it)) })
                    }
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger, "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.getDiagnostics", codec)
                if (api == null) channel.setMessageHandler(null)
                else channel.setMessageHandler { _, reply ->
                    api.getDiagnostics { result ->
                        result.fold({ reply.reply(wrapResult(it)) }, { reply.reply(wrapError(it)) })
                    }
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger, "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.sendProviderMessage", codec)
                if (api == null) channel.setMessageHandler(null)
                else channel.setMessageHandler { message, reply ->
                    val args = message as List<Any?>
                    val typeArg = args[0] as String
                    @Suppress("UNCHECKED_CAST")
                    val payloadArg = args[1] as Map<String, Any?>
                    api.sendProviderMessage(typeArg, payloadArg) { result ->
                        result.fold({ reply.reply(wrapResult(null)) }, { reply.reply(wrapError(it)) })
                    }
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger, "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.getInstalledApps", codec)
                if (api == null) channel.setMessageHandler(null)
                else channel.setMessageHandler { _, reply ->
                    api.getInstalledApps { result ->
                        result.fold({ reply.reply(wrapResult(it)) }, { reply.reply(wrapError(it)) })
                    }
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger, "dev.flutter.pigeon.flutter_vpn_go.VpnHostApi.setExcludedApps", codec)
                if (api == null) channel.setMessageHandler(null)
                else channel.setMessageHandler { message, reply ->
                    val args = message as List<Any?>
                    @Suppress("UNCHECKED_CAST")
                    val packagesArg = args[0] as List<String?>
                    val isWhitelistArg = args[1] as Boolean
                    api.setExcludedApps(packagesArg, isWhitelistArg) { result ->
                        result.fold({ reply.reply(wrapResult(null)) }, { reply.reply(wrapError(it)) })
                    }
                }
            }
        }
    }
}
